### ISSUE TITLE
Configurable ASN/CIDR Input file to use

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/cdncheck#26]
To allow user to extend the known CDN lists by providing known ASN or CIDR with name, a configurable YAMl file can be used to maintain the list, for example:

```yaml
cdn:
  asn:
    akamai:
    - AS12222

    sucuri:
    - AS12222

    leaseweb:
    - AS12222

  cidr:
    fastly:
    - 23.235.32.0/20
    - 43.249.72.0/22
    - 103.244.50.0/24
    - 103.245.222.0/23
    - 103.245.224.0/24
    - 104.156.80.0/20
    - 140.248.64.0/18
    - 140.248.128.0/17
    - 146.75.0.0/17
    - 151.101.0.0/16
    - 157.52.64.0/18
    - 167.82.0.0/17
    - 167.82.128.0/20
    - 167.82.160.0/20
    - 167.82.224.0/20
    - 172.111.64.0/18
    - 185.31.16.0/22
    - 199.27.72.0/21
    - 199.232.0.0/16
```

Currently it's hardcodd here - https://github.com/projectdiscovery/cdncheck/blob/master/ranges.go, with this change, information from YAML file be will be used to populate CIDR ranges based on ASN input for the API service.
